name: CI/CD

on:
  push:
  workflow_dispatch:

defaults:
  run:
    shell: pwsh

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x
      - run: scripts\build.ps1
      - uses: actions/upload-artifact@v4
        with:
          name: nuget
          path: artifacts
          if-no-files-found: 'error'

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
      - uses: actions/download-artifact@v4
        with:
          name: nuget
          path: artifacts
      - run: dotnet nuget push .\artifacts\*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}
      - uses: actions/github-script@v7
        with:
          script: |
            const script = require('./scripts/create-release.js')
            script({github, context})
